name: Create Modules Meta-Files

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*.yaml"
      - ".scripts/create-meta.ps1"
      - "**/DevOpsScripts/**.ps1"
      - "**/DevOpsScripts.Azure/**.ps1"
      - "**/DevOpsScripts.DevOps/**.ps1"
      - "**/DevOpsScripts.OneDrive/**.ps1"
      - "**/DevOpsScripts.Utils/**.ps1"
jobs:
  create-meta-files:
    name: Create Modules Meta-Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Run Script
        run: .scripts/create-meta.ps1
        shell: pwsh

      - name: Commit generated Files
        shell: pwsh
        run: |
          git config --global user.name LemurDaniel
          git config --global user.email landau.daniel.1998@gmail.com
          git add -A

          $changes = git status --porcelain | Measure-Object
          if($changes.Count -gt 0){
            git commit -am "(Automated) Generate Meta-Files"
            git push
          }
