name: Create Modules Meta-Files

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*.yaml"
      - ".scripts/Create-MetaFiles.ps1"
      - "**/DevOpsScripts*/**.ps1"
      - "**/DevOpsScripts*/meta.json"

env:
  MODULE_BASE_NAME: DevOpsScripts
    
jobs:
  create-meta-files:
    name: Create Modules Meta-Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Run Script for creating .psd1 and .psm1 files
        run: .scripts/create-meta.ps1 -moduleBaseName ${{ env.MODULE_BASE_NAME }} -buildPath . -buildNuget $false
        shell: pwsh

      - name: Commit generated Files when changed
        shell: pwsh
        run: |
          git config --global user.name LemurDaniel
          git config --global user.email landau.daniel.1998@gmail.com
          git add -A

          $changes = git status --porcelain | Measure-Object
          if($changes.Count -gt 0){
            git commit -am "(Automated) Generate Meta-Files"
            git push
          }