name: Create Modules Meta-Files

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/Helper*.ps1"
jobs:
  create-meta-files:
    name: Create Modules Meta-Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Run Script
        run: .scripts/create-meta.ps1
        shell: pwsh

      - name: Commit generated Files
        run: |
          git config --global user.name LemurDaniel
          git config --global user.email landau.daniel.1998@gmail.com
          git checkout "${GITHUB_REF:11}"
          git add -A
          git commit -am "(Automated) Generate Meta-Files"
          git push
