name: Create Modules Meta-Files

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*.yaml"
      - ".scripts/create-meta.ps1"
      - "**/DevOpsScripts*/**.ps1"

env:
  MODULE_BASE_NAME: DevOpsScripts
  NUGET_OUT_DIR: ./nugets
  BUILD_PATH: ./build
    
jobs:
  create-meta-files:
    name: Create Modules Meta-Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Run Script
        run: .scripts/create-meta.ps1 -moduleBaseName ${{ env.MODULE_BASE_NAME }} -buildPath . -buildNuget $false
        shell: pwsh

      - name: Commit generated Files
        shell: pwsh
        run: |
          git config --global user.name LemurDaniel
          git config --global user.email landau.daniel.1998@gmail.com
          git add -A

          $changes = git status --porcelain | Measure-Object
          if($changes.Count -gt 0){
            git commit -am "(Automated) Generate Meta-Files"
            git push
          }



      # Testing something
      - name: Use .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x

      - name: Build nuspec files
        run: .scripts/create-meta.ps1 -moduleBaseName ${{ env.MODULE_BASE_NAME }} -buildPath ${{ env.BUILD_PATH }} -buildNuget $true
        shell: pwsh


      - name: Build NuGet package
        shell: pwsh
        run: |
          Get-ChildItem -Path ${{ env.BUILD_PATH }} -Filter '*.nuspec' | ForEach-Object {
            $_
            nuget pack $_.FullName --OutputDirectory  ${{ env.NUGET_OUT_DIR }}
          }

      - name: Push NuGet package
        shell: pwsh
        run: |
          Get-ChildItem -Path ${{ env.NUGET_OUT_DIR }} -Filter '*.nupkg' | ForEach-Object {
            $_
            dotnet nuget push  $_.FullName --api-key ${{ secrets.GH_TOKEN }} --source "github"
          }